name: MiMMO CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install build-essential cmake

      - name: Check formatting
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

      - name: Configure CMake
        run: cmake -S . -B build -DOPENACC=OFF

      - name: Build
        run: cmake --build build

      - name: Unit tests
        run: ctest --test-dir build --output-on-failure
